is_self_encoder: false
spd_log_level: 1 # trace=0, debug=1, info=2, warn=3
joints:
#右臂
  - joint_id: 0
    slave_id: 2         # 填写实际的从站ID
    sub_id: 1           # 在从站下的子ID
    card_slave_id: 3    # 填写控制卡的从站ID
    brake_addr: 0x2010
    torque_addr: 0x2002
    joint_params:

  - joint_id: 1
    slave_id: 2
    sub_id: 2
    card_slave_id: 3
    brake_addr: 0x2009
    torque_addr: 0x2001
    joint_params:

  - joint_id: 2
    slave_id: 4
    sub_id: 1
    card_slave_id: 5
    brake_addr: 0x2010
    torque_addr: 0x2002
    joint_params:

  - joint_id: 3
    slave_id: 4
    sub_id: 2
    card_slave_id: 5
    brake_addr: 0x2009
    torque_addr: 0x2001
    joint_params:
      
  - joint_id: 4 
    slave_id: 6
    sub_id: 2
    card_slave_id: 7
    brake_addr: 0x2008
    torque_addr: 0x2002
    joint_params:

  - joint_id: 5
    slave_id: 6
    sub_id: 1
    card_slave_id: 7
    brake_addr: 0x2008
    torque_addr: 0x2001
    joint_params:

  - joint_id: 6
    slave_id: 6
    sub_id: 0
    card_slave_id: 7
    brake_addr: 0x2008
    torque_addr: 0x2000
    joint_params:

# 左臂
  - joint_id: 7
    slave_id: 8       # 填写实际的从站ID
    sub_id: 1         # 在从站下的子ID
    card_slave_id: 9    # 填写控制卡的从站ID
    brake_addr: 0x2010
    torque_addr: 0x2002
    joint_params:

  - joint_id: 8
    slave_id: 8
    sub_id: 2
    card_slave_id: 9
    brake_addr: 0x2009
    torque_addr: 0x2001
    joint_params:

  - joint_id: 9
    slave_id: 10
    sub_id: 1
    card_slave_id: 11
    brake_addr: 0x2010
    torque_addr: 0x2002
    brand: 0
    joint_params:

  - joint_id: 10
    slave_id: 10
    sub_id: 2
    card_slave_id: 11
    brake_addr: 0x2009
    torque_addr: 0x2001
    brand: 0
    joint_params:
      
  - joint_id: 11 
    slave_id: 12
    sub_id: 2
    card_slave_id: 13
    brake_addr: 0x2008
    torque_addr: 0x2002
    joint_params:

  - joint_id: 12
    slave_id: 12
    sub_id: 1
    card_slave_id: 13
    brake_addr: 0x2008
    torque_addr: 0x2001
    joint_params:

  - joint_id: 13
    slave_id: 12
    sub_id: 0
    card_slave_id: 13
    brake_addr: 0x2008
    torque_addr: 0x2000
    joint_params:

