master:
  id: 0 # 填写实际的主站ID（必须唯一）
  cpu_set:  6 #指定ethercat的实时任务绑定到哪个核心
  frequency: 1000
  
slaves: #(右臂+左臂)
  - position: 0
    alias: 0
    vendor_id: 0x00100000
    product_code: 0x10f40931
    name: "IF1100_6SW"

  - position: 1
    alias: 0
    vendor_id: 0x00100000
    product_code: 0x10f40932
    name: "IF1100_6SW Sub-device"

  # 右臂
  - position: 2
    alias: 0
    vendor_id: 0x0000116d
    product_code: 0x80009001
    name: "ZDL-Robotics Driver"
    need_dc: true

  - position: 3
    alias: 0
    vendor_id: 0x0000116d
    product_code: 0x00009002
    name: "ZDL-Robotics HUB"
    need_dc: true

  - position: 4
    alias: 0
    vendor_id: 0x0000116d
    product_code: 0x00009001
    name: "ZDL-Robotics Driver"
    need_dc: true

  - position: 5
    alias: 0
    vendor_id: 0x0000116d
    product_code: 0x00009002
    name: "ZDL-Robotics HUB"
    need_dc: true

  - position: 6
    alias: 0
    vendor_id: 0x0000116d
    product_code: 0x00009001
    name: "ZDL-Robotics Driver"
    need_dc: true

  - position: 7
    alias: 0
    vendor_id: 0x0000116d
    product_code: 0x00009002
    name: "ZDL-Robotics HUB"
    need_dc: true

    # 左臂
  - position: 8
    alias: 0
    vendor_id: 0x0000116d
    product_code: 0x00009001
    name: "ZDL-Robotics Driver"
    need_dc: true

  - position: 9
    alias: 0
    vendor_id: 0x0000116d
    product_code: 0x00009002
    name: "ZDL-Robotics HUB"
    need_dc: true

  - position: 10
    alias: 0
    vendor_id: 0x0000116d
    product_code: 0x00009001
    name: "ZDL-Robotics Driver"
    need_dc: true

  - position: 11
    alias: 0
    vendor_id: 0x0000116d
    product_code: 0x00009002
    name: "ZDL-Robotics HUB"
    need_dc: true

  - position: 12
    alias: 0
    vendor_id: 0x0000116d
    product_code: 0x00009001
    name: "ZDL-Robotics Driver"
    need_dc: true

  - position: 13
    alias: 0
    vendor_id: 0x0000116d
    product_code: 0x00009002
    name: "ZDL-Robotics HUB"
    need_dc: true


 
