joints: #双臂脖子整机(注意，限位是根据关节安装位置来确定的,需要对着实机用滑条确认一下方向)
  - joint_id: 0
    slave_id: 1       # 填写实际的从站ID
    brand: 1    #关节品牌 0:ZDL-Robotics  1:Ti5Robot 
    joint_params:
      encoder_type: 0 #编码器类型 双编=0，单编=1
      bits: 18      #编码器位数
      ratio: 1      #减速比
      zero_position_deg: 0   #零位的关节角
      upper_limit_deg: 90   #关节角上限
      lower_limit_deg: -90  #关节角下限
      round_flag: true  # 方向标志（true/false）

  - joint_id: 1 
    slave_id: 2
    brand: 1
    joint_params:
      encoder_type: 0 #编码器类型 双编=0，单编=1
      bits: 18      #编码器位数
      ratio: 1      #减速比
      zero_position_deg: 0   #零位的关节角
      upper_limit_deg: 100   #关节角上限
      lower_limit_deg: -100  #关节角下限
      round_flag: false  # 方向标志（true/false）

  - joint_id: 2
    slave_id: 3
    brand: 1
    joint_params:
      encoder_type: 0 #编码器类型 双编=0，单编=1
      bits: 18      #编码器位数
      ratio: 1      #减速比
      zero_position_deg: 0   #零位的关节角
      upper_limit_deg: 90   #关节角上限
      lower_limit_deg: -135  #关节角下限
      round_flag: false  # 方向标志（true/false）

  - joint_id: 3
    slave_id: 4
    brand: 1
    joint_params:
      encoder_type: 0 #编码器类型 双编=0，单编=1
      bits: 18      #编码器位数
      ratio: 1      #减速比
      zero_position_deg: 0   #零位的关节角
      upper_limit_deg: 90   #关节角上限
      lower_limit_deg: -135  #关节角下限
      round_flag: flase  # 方向标志（true/false）
      
  - joint_id: 4 
    slave_id: 5
    brand: 1
    joint_params:
      encoder_type: 0 #编码器类型 双编=0，单编=1
      bits: 18      #编码器位数
      ratio: 1      #减速比
      zero_position_deg: 0   #零位的关节角
      upper_limit_deg: 90   #关节角上限
      lower_limit_deg: -90  #关节角下限
      round_flag: true  # 方向标志（true/false）

  - joint_id: 5
    slave_id: 6
    brand: 1
    joint_params:
      encoder_type: 0 #编码器类型 双编=0，单编=1
      bits: 18      #编码器位数
      ratio: 1      #减速比
      zero_position_deg: 0   #零位的关节角
      upper_limit_deg: 50   #关节角上限
      lower_limit_deg: -50  #关节角下限
      round_flag: false  # 方向标志（true/false）

  - joint_id: 6
    slave_id: 7
    brand: 1
    joint_params:
      encoder_type: 0 #编码器类型 双编=0，单编=1
      bits: 18      #编码器位数
      ratio: 1      #减速比
      zero_position_deg: 0   #零位的关节角
      upper_limit_deg: 30   #关节角上限
      lower_limit_deg: -30  #关节角下限
      round_flag: false  # 方向标志（true/false）
      
  - joint_id: 7
    slave_id: 10       # 填写实际的从站ID
    brand: 1
    joint_params:
      encoder_type: 0 #编码器类型 双编=0，单编=1
      bits: 18      #编码器位数
      ratio: 1      #减速比
      zero_position_deg: 0  #零位的关节角
      upper_limit_deg: 90   #关节角上限
      lower_limit_deg: -90  #关节角下限
      round_flag: false  # 方向标志（true/false）

  - joint_id: 8
    slave_id: 11
    brand: 1
    joint_params:
      encoder_type: 0 #编码器类型 双编=0，单编=1
      bits: 18      #编码器位数
      ratio: 1      #减速比
      zero_position_deg: 0   #零位的关节角
      upper_limit_deg: 100   #关节角上限
      lower_limit_deg: -100  #关节角下限
      round_flag: true  # 方向标志（true/false）

  - joint_id: 9
    slave_id: 12
    brand: 1
    joint_params:
      encoder_type: 0 #编码器类型 双编=0，单编=1
      bits: 18      #编码器位数
      ratio: 1      #减速比
      zero_position_deg: 0   #零位的关节角
      upper_limit_deg: 90   #关节角上限
      lower_limit_deg: -90  #关节角下限
      round_flag: false  # 方向标志（true/false）

  - joint_id: 10
    slave_id: 13
    brand: 1
    joint_params:
      encoder_type: 0 #编码器类型 双编=0，单编=1
      bits: 18      #编码器位数
      ratio: 1      #减速比
      zero_position_deg: 0   #零位的关节角
      upper_limit_deg: 135   #关节角上限
      lower_limit_deg: -90  #关节角下限
      round_flag: true  # 方向标志（true/false）
      
  - joint_id: 11
    slave_id: 14
    brand: 1
    joint_params:
      encoder_type: 0 #编码器类型 双编=0，单编=1
      bits: 18      #编码器位数
      ratio: 1      #减速比
      zero_position_deg: 0   #零位的关节角
      upper_limit_deg: 90   #关节角上限
      lower_limit_deg: -90  #关节角下限
      round_flag: true  # 方向标志（true/false）

  - joint_id: 12
    slave_id: 15
    brand: 1
    joint_params:
      encoder_type: 0 #编码器类型 双编=0，单编=1
      bits: 18      #编码器位数
      ratio: 1      #减速比
      zero_position_deg:  0  #零位的关节角
      upper_limit_deg: 50   #关节角上限
      lower_limit_deg: -50  #关节角下限
      round_flag: true  # 方向标志（true/false）

  - joint_id: 13
    slave_id: 16
    brand: 1
    joint_params:
      encoder_type: 0 #编码器类型 双编=0，单编=1
      bits: 18      #编码器位数
      ratio: 1      #减速比
      zero_position_deg: 0   #零位的关节角
      upper_limit_deg: 30   #关节角上限
      lower_limit_deg: -30  #关节角下限
      round_flag: false  # 方向标志（true/false）
      
#   - joint_id: 14
#     slave_id: 19       # 填写实际的从站ID
#     brand: 1
#     joint_params:
#       encoder_type: 1 #编码器类型 双编=0，单编=1
#       bits: 16      #编码器位数
#       ratio: 51      #减速比
#       zero_position_deg: 0   #零位的关节角
#       upper_limit_deg: 18   #关节角上限
#       lower_limit_deg: -18  #关节角下限
#       round_flag: true  # 方向标志（true/false）

#   - joint_id: 15
#     slave_id: 20
#     brand: 1
#     joint_params:
#       encoder_type: 1 #编码器类型 双编=0，单编=1
#       bits: 16      #编码器位数
#       ratio: 51      #减速比
#       zero_position_deg: 0   #零位的关节角
#       upper_limit_deg: 18   #关节角上限
#       lower_limit_deg: -18  #关节角下限
#       round_flag: false  # 方向标志（true/false）

# hands: 
#      - hand_id: 0
#        slave_id: 8       # 填写实际的从站ID
       
#      - hand_id: 1
#        slave_id: 17       # 填写实际的从站ID

