/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: csp_command.h
  Source: /home/root/workspace/zdl-controller-toolkit/idl/csp_command.idl
  Cyclone DDS: V0.10.5

*****************************************************************/
#ifndef DDSC_CSP_COMMAND_H
#define DDSC_CSP_COMMAND_H

#include "dds/ddsc/dds_public_impl.h"

#ifdef __cplusplus
extern "C" {
#endif

typedef struct zdl_msg_dds__CSPCommand
{
  double timestamp;
  double joint[36];
} zdl_msg_dds__CSPCommand;

extern const dds_topic_descriptor_t zdl_msg_dds__CSPCommand_desc;

#define zdl_msg_dds__CSPCommand__alloc() \
((zdl_msg_dds__CSPCommand*) dds_alloc (sizeof (zdl_msg_dds__CSPCommand)));

#define zdl_msg_dds__CSPCommand_free(d,o) \
dds_sample_free ((d), &zdl_msg_dds__CSPCommand_desc, (o))

#ifdef __cplusplus
}
#endif

#endif /* DDSC_CSP_COMMAND_H */
