/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: disable.h
  Source: /home/root/workspace/dds_ui_cmd_server/idl/disable.idl
  Cyclone DDS: V0.10.5

*****************************************************************/
#ifndef DDSC_DISABLE_H
#define DDSC_DISABLE_H

#include "dds/ddsc/dds_public_impl.h"

#ifdef __cplusplus
extern "C" {
#endif

typedef struct zdl_msg_dds__DisableRequest
{
  uint32_t request_id;
} zdl_msg_dds__DisableRequest;

extern const dds_topic_descriptor_t zdl_msg_dds__DisableRequest_desc;

#define zdl_msg_dds__DisableRequest__alloc() \
((zdl_msg_dds__DisableRequest*) dds_alloc (sizeof (zdl_msg_dds__DisableRequest)));

#define zdl_msg_dds__DisableRequest_free(d,o) \
dds_sample_free ((d), &zdl_msg_dds__DisableRequest_desc, (o))

#ifdef __cplusplus
}
#endif

#endif /* DDSC_DISABLE_H */
