/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: enable.h
  Source: /home/root/workspace/dds_ui_cmd_server/idl/enable.idl
  Cyclone DDS: V0.10.5

*****************************************************************/
#ifndef DDSC_ENABLE_H
#define DDSC_ENABLE_H

#include "dds/ddsc/dds_public_impl.h"

#ifdef __cplusplus
extern "C" {
#endif

typedef enum zdl_msg_dds__EnableMode
{
  zdl_msg_dds__kCSP,
  zdl_msg_dds__kCST
} zdl_msg_dds__EnableMode;

#define zdl_msg_dds__EnableMode__alloc() \
((zdl_msg_dds__EnableMode*) dds_alloc (sizeof (zdl_msg_dds__EnableMode)));

typedef struct zdl_msg_dds__EnableRequest
{
  uint32_t request_id;
  zdl_msg_dds__EnableMode request_mode;
} zdl_msg_dds__EnableRequest;

extern const dds_topic_descriptor_t zdl_msg_dds__EnableRequest_desc;

#define zdl_msg_dds__EnableRequest__alloc() \
((zdl_msg_dds__EnableRequest*) dds_alloc (sizeof (zdl_msg_dds__EnableRequest)));

#define zdl_msg_dds__EnableRequest_free(d,o) \
dds_sample_free ((d), &zdl_msg_dds__EnableRequest_desc, (o))

#ifdef __cplusplus
}
#endif

#endif /* DDSC_ENABLE_H */
