/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: estop.h
  Source: /home/root/workspace/zdl-controller-toolkit/idl/estop.idl
  Cyclone DDS: V0.10.5

*****************************************************************/
#ifndef DDSC_ESTOP_H
#define DDSC_ESTOP_H

#include "dds/ddsc/dds_public_impl.h"

#ifdef __cplusplus
extern "C" {
#endif

typedef struct zdl_msg_dds__EStopRequest
{
  uint32_t request_id;
} zdl_msg_dds__EStopRequest;

extern const dds_topic_descriptor_t zdl_msg_dds__EStopRequest_desc;

#define zdl_msg_dds__EStopRequest__alloc() \
((zdl_msg_dds__EStopRequest*) dds_alloc (sizeof (zdl_msg_dds__EStopRequest)));

#define zdl_msg_dds__EStopRequest_free(d,o) \
dds_sample_free ((d), &zdl_msg_dds__EStopRequest_desc, (o))

#ifdef __cplusplus
}
#endif

#endif /* DDSC_ESTOP_H */
