/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: jog_command.h
  Source: /home/root/workspace/dds_ui_cmd_server/idl/jog_command.idl
  Cyclone DDS: V0.10.5

*****************************************************************/
#ifndef DDSC_JOG_COMMAND_H
#define DDSC_JOG_COMMAND_H

#include "dds/ddsc/dds_public_impl.h"

#ifdef __cplusplus
extern "C" {
#endif

typedef enum zdl_msg_dds__Direction
{
  zdl_msg_dds__FORWARD,
  zdl_msg_dds__BACKWARD
} zdl_msg_dds__Direction;

#define zdl_msg_dds__Direction__alloc() \
((zdl_msg_dds__Direction*) dds_alloc (sizeof (zdl_msg_dds__Direction)));

typedef struct zdl_msg_dds__JogCommand
{
  int32_t joint_id;
  zdl_msg_dds__Direction direction;
  bool active;
} zdl_msg_dds__JogCommand;

extern const dds_topic_descriptor_t zdl_msg_dds__JogCommand_desc;

#define zdl_msg_dds__JogCommand__alloc() \
((zdl_msg_dds__JogCommand*) dds_alloc (sizeof (zdl_msg_dds__JogCommand)));

#define zdl_msg_dds__JogCommand_free(d,o) \
dds_sample_free ((d), &zdl_msg_dds__JogCommand_desc, (o))

#ifdef __cplusplus
}
#endif

#endif /* DDSC_JOG_COMMAND_H */
