/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: return_zero.h
  Source: /home/root/workspace/dds_ui_cmd_server/idl/return_zero.idl
  Cyclone DDS: V0.10.5

*****************************************************************/
#ifndef DDSC_RETURN_ZERO_H
#define DDSC_RETURN_ZERO_H

#include "dds/ddsc/dds_public_impl.h"

#ifdef __cplusplus
extern "C" {
#endif

typedef struct zdl_msg_dds__ReturnZeroRequest
{
  uint32_t request_id;
} zdl_msg_dds__ReturnZeroRequest;

extern const dds_topic_descriptor_t zdl_msg_dds__ReturnZeroRequest_desc;

#define zdl_msg_dds__ReturnZeroRequest__alloc() \
((zdl_msg_dds__ReturnZeroRequest*) dds_alloc (sizeof (zdl_msg_dds__ReturnZeroRequest)));

#define zdl_msg_dds__ReturnZeroRequest_free(d,o) \
dds_sample_free ((d), &zdl_msg_dds__ReturnZeroRequest_desc, (o))

#ifdef __cplusplus
}
#endif

#endif /* DDSC_RETURN_ZERO_H */
