/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: robot_state.h
  Source: /home/root/workspace/zdl-controller-toolkit/idl/robot_state.idl
  Cyclone DDS: V0.10.5

*****************************************************************/
#ifndef DDSC_ROBOT_STATE_H
#define DDSC_ROBOT_STATE_H

#include "dds/ddsc/dds_public_impl.h"

#ifdef __cplusplus
extern "C" {
#endif

typedef enum zdl_msg_dds__state_RobotError
{
  zdl_msg_dds__state_OK,
  zdl_msg_dds__state_kEmergencyStop,
  zdl_msg_dds__state_kExternalEmergencyStop,
  zdl_msg_dds__state_kPoseOverLimit,
  zdl_msg_dds__state_kJointOverTemp,
  zdl_msg_dds__state_kEncoderFault,
  zdl_msg_dds__state_kJointError,
  zdl_msg_dds__state_kCollisionDetected,
  zdl_msg_dds__state_kCommunicationLost
} zdl_msg_dds__state_RobotError;

#define zdl_msg_dds__state_RobotError__alloc() \
((zdl_msg_dds__state_RobotError*) dds_alloc (sizeof (zdl_msg_dds__state_RobotError)));

typedef enum zdl_msg_dds__state_CurrentMode
{
  zdl_msg_dds__state_kNotStart,
  zdl_msg_dds__state_kNotEnable,
  zdl_msg_dds__state_kCSP,
  zdl_msg_dds__state_kCST,
  zdl_msg_dds__state_kOther
} zdl_msg_dds__state_CurrentMode;

#define zdl_msg_dds__state_CurrentMode__alloc() \
((zdl_msg_dds__state_CurrentMode*) dds_alloc (sizeof (zdl_msg_dds__state_CurrentMode)));

typedef enum zdl_msg_dds__state_CurrentMission
{
  zdl_msg_dds__state_kUnavailable,
  zdl_msg_dds__state_kIdle,
  zdl_msg_dds__state_kHoming,
  zdl_msg_dds__state_kJog,
  zdl_msg_dds__state_kReturnToZero,
  zdl_msg_dds__state_kDrag,
  zdl_msg_dds__state_kJointImpedance,
  zdl_msg_dds__state_kCartImpedance,
  zdl_msg_dds__state_kUserCSP,
  zdl_msg_dds__state_kUserCST,
  zdl_msg_dds__state_kFoldedWaistControl
} zdl_msg_dds__state_CurrentMission;

#define zdl_msg_dds__state_CurrentMission__alloc() \
((zdl_msg_dds__state_CurrentMission*) dds_alloc (sizeof (zdl_msg_dds__state_CurrentMission)));

typedef enum zdl_msg_dds__state_CurrentArmMode
{
  zdl_msg_dds__state_kDualArm,
  zdl_msg_dds__state_kLeftArmOnly,
  zdl_msg_dds__state_kRightArmOnly,
  zdl_msg_dds__state_kFoldedWaistOnly,
  zdl_msg_dds__state_kLeftArmWithHand
} zdl_msg_dds__state_CurrentArmMode;

#define zdl_msg_dds__state_CurrentArmMode__alloc() \
((zdl_msg_dds__state_CurrentArmMode*) dds_alloc (sizeof (zdl_msg_dds__state_CurrentArmMode)));

typedef struct zdl_msg_dds__state_JointState7
{
  uint16_t status_word[7];
  uint16_t error_code[7];
  int16_t mode_of_operation[7];
  double q[7];
  double q_d[7];
  double q_e[7];
  double dq[7];
  double tau_J[7];
} zdl_msg_dds__state_JointState7;

extern const dds_topic_descriptor_t zdl_msg_dds__state_JointState7_desc;

#define zdl_msg_dds__state_JointState7__alloc() \
((zdl_msg_dds__state_JointState7*) dds_alloc (sizeof (zdl_msg_dds__state_JointState7)));

#define zdl_msg_dds__state_JointState7_free(d,o) \
dds_sample_free ((d), &zdl_msg_dds__state_JointState7_desc, (o))

typedef struct zdl_msg_dds__state_JointState4
{
  uint16_t status_word[4];
  uint16_t error_code[4];
  int16_t mode_of_operation[4];
  double q[4];
  double q_d[4];
  double q_e[4];
  double dq[4];
  double tau_J[4];
} zdl_msg_dds__state_JointState4;

extern const dds_topic_descriptor_t zdl_msg_dds__state_JointState4_desc;

#define zdl_msg_dds__state_JointState4__alloc() \
((zdl_msg_dds__state_JointState4*) dds_alloc (sizeof (zdl_msg_dds__state_JointState4)));

#define zdl_msg_dds__state_JointState4_free(d,o) \
dds_sample_free ((d), &zdl_msg_dds__state_JointState4_desc, (o))

typedef struct zdl_msg_dds__state_JointState2
{
  uint16_t status_word[2];
  uint16_t error_code[2];
  int16_t mode_of_operation[2];
  double q[2];
  double q_d[2];
  double q_e[2];
  double dq[2];
  double tau_J[2];
} zdl_msg_dds__state_JointState2;

extern const dds_topic_descriptor_t zdl_msg_dds__state_JointState2_desc;

#define zdl_msg_dds__state_JointState2__alloc() \
((zdl_msg_dds__state_JointState2*) dds_alloc (sizeof (zdl_msg_dds__state_JointState2)));

#define zdl_msg_dds__state_JointState2_free(d,o) \
dds_sample_free ((d), &zdl_msg_dds__state_JointState2_desc, (o))

typedef struct zdl_msg_dds__state_ArmState
{
  struct zdl_msg_dds__state_JointState7 joint_state;
  double dq_d[7];
  double tau_Js[7];
  double tau_J_d[7];
  double O_T_EE[16];
  double O_T_EE_d[16];
  double m_total;
  double I_total[9];
  double F_x_Ctotal[3];
  double joint_k_gains[7];
  double joint_d_gains[7];
  double stiffness[6];
  double damping[6];
} zdl_msg_dds__state_ArmState;

extern const dds_topic_descriptor_t zdl_msg_dds__state_ArmState_desc;

#define zdl_msg_dds__state_ArmState__alloc() \
((zdl_msg_dds__state_ArmState*) dds_alloc (sizeof (zdl_msg_dds__state_ArmState)));

#define zdl_msg_dds__state_ArmState_free(d,o) \
dds_sample_free ((d), &zdl_msg_dds__state_ArmState_desc, (o))

typedef struct zdl_msg_dds__state_WaistState
{
  struct zdl_msg_dds__state_JointState4 joint_state;
} zdl_msg_dds__state_WaistState;

extern const dds_topic_descriptor_t zdl_msg_dds__state_WaistState_desc;

#define zdl_msg_dds__state_WaistState__alloc() \
((zdl_msg_dds__state_WaistState*) dds_alloc (sizeof (zdl_msg_dds__state_WaistState)));

#define zdl_msg_dds__state_WaistState_free(d,o) \
dds_sample_free ((d), &zdl_msg_dds__state_WaistState_desc, (o))

typedef struct zdl_msg_dds__state_HandState
{
  struct zdl_msg_dds__state_JointState7 joint_state;
} zdl_msg_dds__state_HandState;

extern const dds_topic_descriptor_t zdl_msg_dds__state_HandState_desc;

#define zdl_msg_dds__state_HandState__alloc() \
((zdl_msg_dds__state_HandState*) dds_alloc (sizeof (zdl_msg_dds__state_HandState)));

#define zdl_msg_dds__state_HandState_free(d,o) \
dds_sample_free ((d), &zdl_msg_dds__state_HandState_desc, (o))

typedef struct zdl_msg_dds__state_HeadState
{
  struct zdl_msg_dds__state_JointState2 joint_state;
} zdl_msg_dds__state_HeadState;

extern const dds_topic_descriptor_t zdl_msg_dds__state_HeadState_desc;

#define zdl_msg_dds__state_HeadState__alloc() \
((zdl_msg_dds__state_HeadState*) dds_alloc (sizeof (zdl_msg_dds__state_HeadState)));

#define zdl_msg_dds__state_HeadState_free(d,o) \
dds_sample_free ((d), &zdl_msg_dds__state_HeadState_desc, (o))

typedef struct zdl_msg_dds__state_WheelState
{
  struct zdl_msg_dds__state_JointState2 joint_state;
} zdl_msg_dds__state_WheelState;

extern const dds_topic_descriptor_t zdl_msg_dds__state_WheelState_desc;

#define zdl_msg_dds__state_WheelState__alloc() \
((zdl_msg_dds__state_WheelState*) dds_alloc (sizeof (zdl_msg_dds__state_WheelState)));

#define zdl_msg_dds__state_WheelState_free(d,o) \
dds_sample_free ((d), &zdl_msg_dds__state_WheelState_desc, (o))

typedef struct zdl_msg_dds__state_RobotState
{
  struct zdl_msg_dds__state_ArmState left_arm;
  struct zdl_msg_dds__state_ArmState right_arm;
  struct zdl_msg_dds__state_HandState left_hand;
  struct zdl_msg_dds__state_HandState right_hand;
  struct zdl_msg_dds__state_WaistState folded_waist;
  struct zdl_msg_dds__state_WheelState wheel;
  struct zdl_msg_dds__state_HeadState head;
  zdl_msg_dds__state_RobotError current_errors;
  zdl_msg_dds__state_CurrentMode current_mode;
  zdl_msg_dds__state_CurrentMission current_mission;
  zdl_msg_dds__state_CurrentArmMode current_arm_mode;
  double time;
} zdl_msg_dds__state_RobotState;

extern const dds_topic_descriptor_t zdl_msg_dds__state_RobotState_desc;

#define zdl_msg_dds__state_RobotState__alloc() \
((zdl_msg_dds__state_RobotState*) dds_alloc (sizeof (zdl_msg_dds__state_RobotState)));

#define zdl_msg_dds__state_RobotState_free(d,o) \
dds_sample_free ((d), &zdl_msg_dds__state_RobotState_desc, (o))

#ifdef __cplusplus
}
#endif

#endif /* DDSC_ROBOT_STATE_H */
