/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: set_zero_position.h
  Source: /home/root/workspace/dds_ui_cmd_server/idl/set_zero_position.idl
  Cyclone DDS: V0.10.5

*****************************************************************/
#ifndef DDSC_SET_ZERO_POSITION_H
#define DDSC_SET_ZERO_POSITION_H

#include "dds/ddsc/dds_public_impl.h"

#ifdef __cplusplus
extern "C" {
#endif

typedef struct zdl_msg_dds__SetZeroPositionRequest
{
  uint32_t request_id;
} zdl_msg_dds__SetZeroPositionRequest;

extern const dds_topic_descriptor_t zdl_msg_dds__SetZeroPositionRequest_desc;

#define zdl_msg_dds__SetZeroPositionRequest__alloc() \
((zdl_msg_dds__SetZeroPositionRequest*) dds_alloc (sizeof (zdl_msg_dds__SetZeroPositionRequest)));

#define zdl_msg_dds__SetZeroPositionRequest_free(d,o) \
dds_sample_free ((d), &zdl_msg_dds__SetZeroPositionRequest_desc, (o))

#ifdef __cplusplus
}
#endif

#endif /* DDSC_SET_ZERO_POSITION_H */
