/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: start_task.h
  Source: /home/root/workspace/zdl-controller-toolkit/idl/start_task.idl
  Cyclone DDS: V0.10.5

*****************************************************************/
#ifndef DDSC_START_TASK_H
#define DDSC_START_TASK_H

#include "dds/ddsc/dds_public_impl.h"

#ifdef __cplusplus
extern "C" {
#endif

typedef enum zdl_msg_dds__CurrentArmMode
{
  zdl_msg_dds__kDualArm,
  zdl_msg_dds__kLeftArmOnly,
  zdl_msg_dds__kRightArmOnly,
  zdl_msg_dds__kFoldedWaistOnly
} zdl_msg_dds__CurrentArmMode;

#define zdl_msg_dds__CurrentArmMode__alloc() \
((zdl_msg_dds__CurrentArmMode*) dds_alloc (sizeof (zdl_msg_dds__CurrentArmMode)));

typedef struct zdl_msg_dds__Inertia
{
  double ixx;
  double iyy;
  double izz;
  double ixy;
  double ixz;
  double iyz;
} zdl_msg_dds__Inertia;

extern const dds_topic_descriptor_t zdl_msg_dds__Inertia_desc;

#define zdl_msg_dds__Inertia__alloc() \
((zdl_msg_dds__Inertia*) dds_alloc (sizeof (zdl_msg_dds__Inertia)));

#define zdl_msg_dds__Inertia_free(d,o) \
dds_sample_free ((d), &zdl_msg_dds__Inertia_desc, (o))

typedef struct zdl_msg_dds__EndEffector
{
  double m;
  double com[3];
  struct zdl_msg_dds__Inertia inertia;
} zdl_msg_dds__EndEffector;

extern const dds_topic_descriptor_t zdl_msg_dds__EndEffector_desc;

#define zdl_msg_dds__EndEffector__alloc() \
((zdl_msg_dds__EndEffector*) dds_alloc (sizeof (zdl_msg_dds__EndEffector)));

#define zdl_msg_dds__EndEffector_free(d,o) \
dds_sample_free ((d), &zdl_msg_dds__EndEffector_desc, (o))

typedef enum zdl_msg_dds__RobotParts
{
  zdl_msg_dds__kLeftArm,
  zdl_msg_dds__kRightArm,
  zdl_msg_dds__kLeftHand,
  zdl_msg_dds__kRightHand,
  zdl_msg_dds__kHead,
  zdl_msg_dds__kFoldedWaist,
  zdl_msg_dds__kDoubleWheel
} zdl_msg_dds__RobotParts;

#define zdl_msg_dds__RobotParts__alloc() \
((zdl_msg_dds__RobotParts*) dds_alloc (sizeof (zdl_msg_dds__RobotParts)));

#ifndef DDS_SEQUENCE_ZDL_MSG_DDS__ROBOTPARTS_DEFINED
#define DDS_SEQUENCE_ZDL_MSG_DDS__ROBOTPARTS_DEFINED
typedef struct dds_sequence_zdl_msg_dds__RobotParts
{
  uint32_t _maximum;
  uint32_t _length;
  zdl_msg_dds__RobotParts *_buffer;
  bool _release;
} dds_sequence_zdl_msg_dds__RobotParts;

#define dds_sequence_zdl_msg_dds__RobotParts__alloc() \
((dds_sequence_zdl_msg_dds__RobotParts*) dds_alloc (sizeof (dds_sequence_zdl_msg_dds__RobotParts)));

#define dds_sequence_zdl_msg_dds__RobotParts_allocbuf(l) \
((zdl_msg_dds__RobotParts *) dds_alloc ((l) * sizeof (zdl_msg_dds__RobotParts)))
#endif /* DDS_SEQUENCE_ZDL_MSG_DDS__ROBOTPARTS_DEFINED */

typedef struct zdl_msg_dds__StartConfig
{
  zdl_msg_dds__CurrentArmMode arm_mode;
  double distance_between_arm;
  struct zdl_msg_dds__EndEffector left_end_effector;
  struct zdl_msg_dds__EndEffector right_end_effector;
  dds_sequence_zdl_msg_dds__RobotParts part_config;
} zdl_msg_dds__StartConfig;

extern const dds_topic_descriptor_t zdl_msg_dds__StartConfig_desc;

#define zdl_msg_dds__StartConfig__alloc() \
((zdl_msg_dds__StartConfig*) dds_alloc (sizeof (zdl_msg_dds__StartConfig)));

#define zdl_msg_dds__StartConfig_free(d,o) \
dds_sample_free ((d), &zdl_msg_dds__StartConfig_desc, (o))

typedef struct zdl_msg_dds__StartRequest
{
  uint32_t request_id;
  struct zdl_msg_dds__StartConfig config;
} zdl_msg_dds__StartRequest;

extern const dds_topic_descriptor_t zdl_msg_dds__StartRequest_desc;

#define zdl_msg_dds__StartRequest__alloc() \
((zdl_msg_dds__StartRequest*) dds_alloc (sizeof (zdl_msg_dds__StartRequest)));

#define zdl_msg_dds__StartRequest_free(d,o) \
dds_sample_free ((d), &zdl_msg_dds__StartRequest_desc, (o))

#ifdef __cplusplus
}
#endif

#endif /* DDSC_START_TASK_H */
