/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: stop_task.h
  Source: /home/root/workspace/dds_ui_cmd_server/idl/stop_task.idl
  Cyclone DDS: V0.10.5

*****************************************************************/
#ifndef DDSC_STOP_TASK_H
#define DDSC_STOP_TASK_H

#include "dds/ddsc/dds_public_impl.h"

#ifdef __cplusplus
extern "C" {
#endif

typedef struct zdl_msg_dds__StopRequest
{
  uint32_t request_id;
} zdl_msg_dds__StopRequest;

extern const dds_topic_descriptor_t zdl_msg_dds__StopRequest_desc;

#define zdl_msg_dds__StopRequest__alloc() \
((zdl_msg_dds__StopRequest*) dds_alloc (sizeof (zdl_msg_dds__StopRequest)));

#define zdl_msg_dds__StopRequest_free(d,o) \
dds_sample_free ((d), &zdl_msg_dds__StopRequest_desc, (o))

#ifdef __cplusplus
}
#endif

#endif /* DDSC_STOP_TASK_H */
