/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: stop_mission.h
  Source: /home/root/workspace/zdl-controller-toolkit/idl/stop_mission.idl
  Cyclone DDS: V0.10.5

*****************************************************************/
#ifndef DDSC_STOP_MISSION_H
#define DDSC_STOP_MISSION_H

#include "dds/ddsc/dds_public_impl.h"

#ifdef __cplusplus
extern "C" {
#endif

typedef struct zdl_msg_dds__StopMissionRequest
{
  uint32_t request_id;
} zdl_msg_dds__StopMissionRequest;

extern const dds_topic_descriptor_t zdl_msg_dds__StopMissionRequest_desc;

#define zdl_msg_dds__StopMissionRequest__alloc() \
((zdl_msg_dds__StopMissionRequest*) dds_alloc (sizeof (zdl_msg_dds__StopMissionRequest)));

#define zdl_msg_dds__StopMissionRequest_free(d,o) \
dds_sample_free ((d), &zdl_msg_dds__StopMissionRequest_desc, (o))

#ifdef __cplusplus
}
#endif

#endif /* DDSC_STOP_MISSION_H */
