/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: waist_target.h
  Source: /home/root/workspace/dds_ui_cmd_server/idl/waist_target.idl
  Cyclone DDS: V0.10.5

*****************************************************************/
#ifndef DDSC_WAIST_TARGET_H
#define DDSC_WAIST_TARGET_H

#include "dds/ddsc/dds_public_impl.h"

#ifdef __cplusplus
extern "C" {
#endif

typedef struct zdl_msg_dds__WaistTarget
{
  uint32_t request_id;
  double target;
} zdl_msg_dds__WaistTarget;

extern const dds_topic_descriptor_t zdl_msg_dds__WaistTarget_desc;

#define zdl_msg_dds__WaistTarget__alloc() \
((zdl_msg_dds__WaistTarget*) dds_alloc (sizeof (zdl_msg_dds__WaistTarget)));

#define zdl_msg_dds__WaistTarget_free(d,o) \
dds_sample_free ((d), &zdl_msg_dds__WaistTarget_desc, (o))

#ifdef __cplusplus
}
#endif

#endif /* DDSC_WAIST_TARGET_H */
