/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: wheel_stop.h
  Source: /home/root/workspace/dds_ui_cmd_server/idl/wheel_stop.idl
  Cyclone DDS: V0.10.5

*****************************************************************/
#ifndef DDSC_WHEEL_STOP_H
#define DDSC_WHEEL_STOP_H

#include "dds/ddsc/dds_public_impl.h"

#ifdef __cplusplus
extern "C" {
#endif

typedef struct zdl_msg_dds__WheelStop
{
  uint32_t request_id;
} zdl_msg_dds__WheelStop;

extern const dds_topic_descriptor_t zdl_msg_dds__WheelStop_desc;

#define zdl_msg_dds__WheelStop__alloc() \
((zdl_msg_dds__WheelStop*) dds_alloc (sizeof (zdl_msg_dds__WheelStop)));

#define zdl_msg_dds__WheelStop_free(d,o) \
dds_sample_free ((d), &zdl_msg_dds__WheelStop_desc, (o))

#ifdef __cplusplus
}
#endif

#endif /* DDSC_WHEEL_STOP_H */
